### ISSUE TITLE
it caused my game to crash

### ISSUE THREAD

**Issue by nicoandkotori** [ersh1/Precision#1]
this is the crash log:
Crash Log SE, version 2
Code: 0xc0000005.
Address: SkyrimSE.exe+0x73ca0a.
Memory at 0x9b72ffdc could not be read.

Loaded modules:

BaseAddress EndAddress FileName
0x0000000025020000 0x0000000028728000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\SkyrimSE.exe
0x00000000c9a50000 0x00000000c9c48000 C:\Windows\SYSTEM32\ntdll.dll
0x00000000c9950000 0x00000000c9a0d000 C:\Windows\System32\KERNEL32.DLL
0x00000000c7470000 0x00000000c773e000 C:\Windows\System32\KERNELBASE.dll
0x00000000c93a0000 0x00000000c9540000 C:\Windows\System32\USER32.dll
0x00000000c78f0000 0x00000000c7912000 C:\Windows\System32\win32u.dll
0x00000000c7ca0000 0x00000000c7cca000 C:\Windows\System32\GDI32.dll
0x00000000c7170000 0x00000000c727b000 C:\Windows\System32\gdi32full.dll
0x00000000c72d0000 0x00000000c736d000 C:\Windows\System32\msvcp_win.dll
0x00000000c7370000 0x00000000c7470000 C:\Windows\System32\ucrtbase.dll
0x00000000c98a0000 0x00000000c994e000 C:\Windows\System32\ADVAPI32.dll
0x00000000c7b30000 0x00000000c7bce000 C:\Windows\System32\msvcrt.dll
0x00000000c7fd0000 0x00000000c806c000 C:\Windows\System32\sechost.dll
0x00000000c8a20000 0x00000000c8b45000 C:\Windows\System32\RPCRT4.dll
0x00000000c81f0000 0x00000000c8934000 C:\Windows\System32\SHELL32.dll
0x00000000c8b50000 0x00000000c8c7a000 C:\Windows\System32\ole32.dll
0x00000000c9540000 0x00000000c9894000 C:\Windows\System32\combase.dll
0x00000000c8ec0000 0x00000000c8f2b000 C:\Windows\System32\WS2_32.dll
0x00000000c8f30000 0x00000000c939f000 C:\Windows\System32\SETUPAPI.dll
0x00000000c7280000 0x00000000c72ce000 C:\Windows\System32\cfgmgr32.dll
0x000000006f880000 0x000000006f889000 C:\Windows\SYSTEM32\X3DAudio1_7.dll
0x0000000000400000 0x000000000041e000 C:\Windows\SYSTEM32\XINPUT1_3.dll
0x00000000c7920000 0x00000000c7947000 C:\Windows\System32\bcrypt.dll
0x00000000c0ec0000 0x00000000c0f05000 C:\Windows\SYSTEM32\DINPUT8.dll
0x00000000c7bd0000 0x00000000c7c9d000 C:\Windows\System32\OLEAUT32.dll
0x0000000080000000 0x0000000080069000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\binkw64.dll
0x00000000c2190000 0x00000000c229a000 C:\Windows\SYSTEM32\WINHTTP.dll
0x00000000600b0000 0x0000000060191000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\steam_api64.dll
0x00000000c65d0000 0x00000000c660b000 C:\Windows\SYSTEM32\IPHLPAPI.DLL
0x00000000c8cf0000 0x00000000c8cf8000 C:\Windows\System32\PSAPI.DLL
0x00000000b9340000 0x00000000b93ce000 C:\Windows\SYSTEM32\MSVCP140.dll
0x00000000c8dd0000 0x00000000c8e25000 C:\Windows\System32\SHLWAPI.dll
0x00000000c2f90000 0x00000000c2f99000 C:\Windows\SYSTEM32\WSOCK32.dll
0x00000000c2400000 0x00000000c241c000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\d3dx9_42.dll
0x00000000b9310000 0x00000000b932b000 C:\Windows\SYSTEM32\VCRUNTIME140.dll
0x00000000c5a10000 0x00000000c5a1d000 C:\Windows\SYSTEM32\HID.DLL
0x00000000b8310000 0x00000000b8337000 C:\Windows\SYSTEM32\WINMM.dll
0x00000000c5a70000 0x00000000c5b63000 C:\Windows\SYSTEM32\dxgi.dll
0x00000000b92c0000 0x00000000b92cc000 C:\Windows\SYSTEM32\VCRUNTIME140_1.dll
0x00000000a1410000 0x00000000a1d4d000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\d3d11.dll
0x000000008e910000 0x000000008e956000 C:\Windows\SYSTEM32\d3dx11_43.dll
0x0000000042810000 0x0000000042a7f000 C:\Windows\SYSTEM32\D3DCOMPILER_43.dll
0x00000000c8e30000 0x00000000c8e60000 C:\Windows\System32\IMM32.DLL
0x00000000c5270000 0x00000000c5a04000 C:\Windows\SYSTEM32\windows.storage.dll
0x00000000c6bd0000 0x00000000c6c00000 C:\Windows\SYSTEM32\Wldp.dll
0x00000000c8d20000 0x00000000c8dcd000 C:\Windows\System32\SHCORE.dll
0x00000000bb240000 0x00000000bb276000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\skse64_steam_loader.dll
0x00000000bf290000 0x00000000bf29a000 C:\Windows\SYSTEM32\VERSION.dll
0x00000000b7160000 0x00000000b72b2000 C:\Windows\SYSTEM32\inputhost.dll
0x00000000c4760000 0x00000000c4852000 C:\Windows\SYSTEM32\CoreMessaging.dll
0x00000000c2ba0000 0x00000000c2c96000 C:\Windows\SYSTEM32\PROPSYS.dll
0x00000000c30a0000 0x00000000c31f4000 C:\Windows\SYSTEM32\wintypes.dll
0x00000000c7860000 0x00000000c78e2000 C:\Windows\System32\bcryptPrimitives.dll
0x00000000c4400000 0x00000000c475e000 C:\Windows\SYSTEM32\CoreUIComponents.dll
0x00000000c5e70000 0x00000000c5ea3000 C:\Windows\SYSTEM32\ntmarta.dll
0x00000000c5050000 0x00000000c5062000 C:\Windows\SYSTEM32\kernel.appcore.dll
0x00000000c70b0000 0x00000000c70cf000 C:\Windows\SYSTEM32\profapi.dll
0x00000000a3a70000 0x00000000a3bf3000 E:\iniRePather-Skyrim\Mod Organizer 2\usvfs_x64.dll
0x00000000bd230000 0x00000000bd260000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-NetScriptFramework SkyrimSE v18\DLLPlugins\NetScriptFramework.Runtime.dll
0x00000000be500000 0x00000000be6e4000 C:\Windows\SYSTEM32\dbghelp.dll
0x000000007aa30000 0x000000007aa95000 C:\Windows\SYSTEM32\mscoree.dll
0x000000007a980000 0x000000007aa2a000 C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
0x0000000079e40000 0x000000007a975000 C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
0x0000000079e20000 0x0000000079e36000 C:\Windows\SYSTEM32\VCRUNTIME140_CLR0400.dll
0x0000000079d60000 0x0000000079e1d000 C:\Windows\SYSTEM32\ucrtbase_clr0400.dll
0x0000000078760000 0x0000000079d60000 C:\Windows\assembly\NativeImages_v4.0.30319_64\mscorlib\b8493bec853ac702d2188091d76ccffa\mscorlib.ni.dll
0x00000000785c0000 0x000000007870f000 C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
0x00000000bd660000 0x00000000bd680000 C:\Windows\SYSTEM32\amsi.dll
0x00000000c7070000 0x00000000c709e000 C:\Windows\SYSTEM32\USERENV.dll
0x00000000bb9b0000 0x00000000bba2b000 C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2205.7-0\MpOav.dll
0x00000000b72c0000 0x00000000b73ed000 C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2205.7-0\MPCLIENT.DLL
0x00000000c7950000 0x00000000c7aa6000 C:\Windows\System32\CRYPT32.dll
0x00000000c77f0000 0x00000000c7857000 C:\Windows\System32\WINTRUST.dll
0x00000000c6d60000 0x00000000c6d72000 C:\Windows\System32\MSASN1.dll
0x00000000c5a20000 0x00000000c5a43000 C:\Windows\SYSTEM32\gpapi.dll
0x000000006f250000 0x000000006fec1000 C:\Windows\assembly\NativeImages_v4.0.30319_64\System\54c5a8ebfacb96ef1f1af1d732b88f97\System.ni.dll
0x000000006e7d0000 0x000000006f245000 C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Core\5a9aa981acfc11a81b346d71a68d228c\System.Core.ni.dll
0x00000000b75d0000 0x00000000b77bc000 C:\Windows\SYSTEM32\urlmon.dll
0x00000000bd300000 0x00000000bd5b1000 C:\Windows\SYSTEM32\iertutil.dll
0x00000000b75a0000 0x00000000b75c8000 C:\Windows\SYSTEM32\srvcli.dll
0x00000000c66e0000 0x00000000c66ec000 C:\Windows\SYSTEM32\netutils.dll
0x00000000c7030000 0x00000000c7062000 C:\Windows\SYSTEM32\SspiCli.dll
0x0000000052160000 0x0000000052275000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-NetScriptFramework SkyrimSE v18\NetScriptFramework\NetScriptFramework.SkyrimSE.dll
0x0000000051b70000 0x0000000051c8b000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-Engine Fixes v5.6.0\SKSE\Plugins\EngineFixes.dll
0x00000000a3e40000 0x00000000a3ea9000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\tbb.dll
0x00000000a3dd0000 0x00000000a3e32000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\tbbmalloc.dll
0x00000000a3cc0000 0x00000000a3d19000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\INI?????-PrivateProfileRedirector v0.5.2\SKSE\Plugins\PrivateProfileRedirector.dll
0x00000000c6b40000 0x00000000c6b4c000 C:\Windows\SYSTEM32\CRYPTBASE.DLL
0x0000000050ba0000 0x0000000050ceb000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\skse64_1_5_97.dll
0x00000000a3c10000 0x00000000a3c67000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-Add Item Menu v1.14\SKSE\Plugins\AddItemMenuSE.dll
0x00000000a36c0000 0x00000000a3721000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-MoreHUD Inventory Edition\SKSE\Plugins\AHZmoreHUDInventory.dll
0x000000008e130000 0x000000008e1bd000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-MoreHUD\SKSE\Plugins\AHZmoreHUDPlugin.dll
0x00000000a6870000 0x00000000a68b4000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????????-Animated Static Reload Fix v1.01\SKSE\Plugins\AnimatedStaticReload.dll
0x0000000082480000 0x000000008251a000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-Animation Motion Revolution v1.5\SKSE\Plugins\AnimationMotionRevolution.dll
0x0000000099fd0000 0x000000009a02b000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????-Better Jumping v1.8.3\SKSE\Plugins\BetterJumpingSE.dll
0x0000000041d50000 0x0000000041f49000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????????-Better Third Person Selection v0.54\SKSE\Plugins\BetterThirdPersonSelection.dll
0x0000000080360000 0x000000008042f000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-CBPC Physics with Collisions v1.49\SKSE\Plugins\cbp.dll
0x0000000041b60000 0x0000000041d4c000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-SKSE Plugin Chinese\SKSE\Plugins\ChineseInput.dll
0x0000000041700000 0x0000000041b51000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\D3DCOMPILER_47.dll
0x00000000809f0000 0x0000000080a7c000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????????-ConsoleUtilSSE\SKSE\Plugins\ConsoleUtilSSE.dll
0x00000000bb2c0000 0x00000000bb2ef000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\Crash Log SE\skse\plugins\crash_log_se.dll
0x00000000a5b90000 0x00000000a5bc2000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????????-UNDERDOG Animations\SKSE\Plugins\DisableTurnAnimation.dll
0x00000000805a0000 0x0000000080632000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-Dodge Modern Combat Overhaul\SKSE\Plugins\DodgeFramework.dll
0x0000000060c00000 0x0000000060ca9000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-Stop On Slash HitStop v2.2\SKSE\Plugins\dTryHitStop.dll
0x000000008ee40000 0x000000008eead000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\???????-DynamicAnimationReplacer v1.10\SKSE\Plugins\DynamicAnimationReplacer.dll
0x00000000634c0000 0x0000000063550000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????-Elden Counter v1.6\SKSE\Plugins\EldenCounter.dll
0x000000005c6a0000 0x000000005c729000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-ENB Helper SE 1.5\skse\plugins\ENBHelperSE.dll
0x00000000598b0000 0x000000005993f000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\ENB?????-ENB Input Disabler\SKSE\Plugins\ENBInputDisabler.dll
0x00000000af140000 0x00000000af166000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????????-EVLaS v1.3.0\SKSE\Plugins\EVLaS.dll
0x0000000042c10000 0x0000000042c9f000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-Face Discoloration Fix v1.01\SKSE\Plugins\FaceGenFixes.dll
0x00000000a5af0000 0x00000000a5b27000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-FileAccess Interface for Skyrim Scripts v1.3.6\SKSE\Plugins\fiss.dll
0x000000009a230000 0x000000009a274000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-Free Fly CamSKSE\skse\plugins\FreeFlyCam SSE.dll
0x0000000081500000 0x0000000081562000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-Fuz Ro D-oh Silent Voice v1.7.0\SKSE\Plugins\Fuz Ro D'oh.dll
0x000000003fce0000 0x00000000404df000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-HDT SMP v2.11\SKSE\Plugins\hdtSMP64.dll
0x0000000041300000 0x00000000416f3000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\???????-Immersive Equipment Displays v1.4.1\SKSE\Plugins\ImmersiveEquipmentDisplays.dll
0x0000000042760000 0x0000000042805000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????NPC??-I'm Walkin' Here\SKSE\Plugins\ImWalkinHere.dll
0x00000000a47f0000 0x00000000a4828000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\NPC????-Smart NPC Potions\SKSE\plugins\InventoryFunctions64.dll
0x0000000040a70000 0x0000000040da7000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-JContainers v4.1.13\SKSE\Plugins\JContainers64.dll
0x00000000a69c0000 0x00000000a69eb000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\NPC??????-NPC AI Process Pos Fix v4.06\SKSE\Plugins\MaxsuAIProcessFix.dll
0x00000000812b0000 0x00000000812fe000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\???????-Better Combat Escape v0.83\SKSE\Plugins\MaxsuCombatEscape.dll
0x0000000040960000 0x0000000040a6c000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\???-Detection Meter v0.16\SKSE\Plugins\MaxsuDetectionMeter.dll
0x00000000c0e80000 0x00000000c0e94000 C:\Windows\SYSTEM32\MSVCP140_ATOMIC_WAIT.dll
0x0000000080e20000 0x0000000080e66000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????-IFrame Generator v0.91\SKSE\Plugins\MaxsuIFrame.dll
0x0000000080b50000 0x0000000080b9a000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????????-Better PowerAttack Control\SKSE\Plugins\MaxsuPowerAttackControl.dll
0x0000000080810000 0x000000008085a000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-Simple Weapon Swing Parry v1.10\SKSE\Plugins\MaxsuWeaponParry.dll
0x000000003fa50000 0x000000003fb66000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\MCM??-MCM Helper v1.3.0\SKSE\Plugins\MCMHelper.dll
0x0000000041270000 0x00000000412f5000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????????-ADXP Beta v1.3\SKSE\Plugins\MCO.dll
0x00000000802b0000 0x000000008031f000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\???-MiniMap v1.0.1\SKSE\Plugins\MiniMap.dll
0x000000007b810000 0x000000007b880000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\???????-More Informative Console\SKSE\Plugins\MoreInformativeConsole.dll
0x0000000082440000 0x0000000082478000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-One Click Power Attack\SKSE\Plugins\OneClickPowerAttack.dll
0x000000003f8d0000 0x000000003fa41000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-PapyrusUtil v3.9.0\SKSE\Plugins\PapyrusUtil.dll
0x00000000d46e0000 0x00000000d47a0000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-Skyrim's Paraglider\SKSE\plugins\Paraglider.dll
0x000000003f770000 0x000000003f80c000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-Payload Interpreter\SKSE\Plugins\PayloadFramework.dll
0x000000003f6d0000 0x000000003f769000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-Crafting Recipe Distributor v1.2\skse\plugins\po3_CraftingRecipeDistributor.dll
0x000000003f630000 0x000000003f6c8000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\???????-Enhanced Invisibility\skse\plugins\po3_EnhancedInvisibility.dll
0x000000003f580000 0x000000003f621000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-Frozen Electrocuted Combustion v4.9.5\skse\plugins\po3_FEC.dll
0x000000003f4e0000 0x000000003f580000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-Security Overhaul SKSE Lock Variations v1.0\skse\plugins\po3_LockVariations.dll
0x000000003f2e0000 0x000000003f4e0000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????-Papyrus Extender v4.5.5\skse\plugins\po3_PapyrusExtender.dll
0x000000003eae0000 0x000000003ebd6000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????????-Spell Perk Item Distributor v5.2.0\skse\plugins\po3_SpellPerkItemDistributor.dll
0x000000003ea30000 0x000000003ead2000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-Splashes of Skyrim v1.3\skse\plugins\po3_SplashesOfSkyrim.dll
0x000000003e970000 0x000000003ea24000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????-powerofthree's Tweaks v1.4.1\skse\plugins\po3_Tweaks.dll
0x000000003e8c0000 0x000000003e964000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-Wash That Blood Off\skse\plugins\po3_WashThatBloodOff.dll
0x000000003e770000 0x000000003e8be000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\Precision\SKSE\Plugins\Precision.dll
0x00000000a3c90000 0x00000000a3cb3000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????-Skyrim Priority v3.0.0\SKSE\Plugins\PriorityMod.dll
0x000000003e6d0000 0x000000003e762000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\???????-Parallax Shader Fix v1.0 BETA\skse\plugins\ShaderTools.dll
0x000000003e5b0000 0x000000003e6c4000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-Show Stats v1.0\SKSE\Plugins\ShowStats.dll
0x000000003e510000 0x000000003e5a4000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\??????-Simple Dual Sheath\SKSE\Plugins\SimpleDualSheath.dll
0x000000003e320000 0x000000003e504000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-RaceMenu Special Edition v0.4.16\SKSE\Plugins\skee64.dll
0x000000003e200000 0x000000003e319000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????-SmoothCam\SKSE\Plugins\SmoothCam.dll
0x00000000bda00000 0x00000000bda2c000 C:\Windows\SYSTEM32\dbgcore.DLL
0x0000000061600000 0x0000000061659000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????-FPS Stabilizer v1.3.0\SKSE\Plugins\SSEFpsStabilizer.dll
0x000000003e170000 0x000000003e1f9000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\ESC????-Stay At System Page\SKSE\Plugins\StayAtSystemPageSE.dll
0x000000003e0c0000 0x000000003e169000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-True Directional Movement v2.2.1\SKSE\Plugins\TrueDirectionalMovement.dll
0x000000003e010000 0x000000003e0bd000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\???????-TrueHUD v1.1.4\SKSE\Plugins\TrueHUD.dll
0x000000003db90000 0x000000003dc59000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\?????-ValhallaCombat v0.9.9\SKSE\Plugins\valhallaCombat.dll
0x000000007b490000 0x000000007b4dd000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-zxlice's ultimate potion animation v1.5.0\SKSE\plugins\zxlice's ultimate potion animation.dll
0x00000000c4a80000 0x00000000c4b1e000 C:\Windows\system32\uxtheme.dll
0x00000000c80d0000 0x00000000c81e5000 C:\Windows\System32\MSCTF.dll
0x00000000b73f0000 0x00000000b74e9000 C:\Windows\SYSTEM32\textinputframework.dll
0x000000008f680000 0x000000008f86b000 C:\Windows\system32\SogouTSF.ime
0x00000000b8500000 0x00000000b8507000 C:\Windows\SYSTEM32\MSIMG32.dll
0x000000008d440000 0x000000008dcc9000 C:\Windows\system32\SogouPy.ime
0x00000000a54e0000 0x00000000a5546000 C:\Windows\SYSTEM32\OLEACC.dll
0x00000000c7f10000 0x00000000c7fb9000 C:\Windows\System32\clbcatq.dll
0x000000009a540000 0x000000009a57a000 C:\Windows\system32\msctfp.dll
0x000000008c070000 0x000000008c2da000 D:\SogouInput\Components\PicFace\1.1.0.1879\PicFace64.dll
0x00000000c8940000 0x00000000c8a1a000 C:\Windows\System32\COMDLG32.dll
0x00000000a4c90000 0x00000000a4d40000 C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\COMCTL32.dll
0x0000000010000000 0x000000001011d000 D:\SogouInput\9.5.0.3517\Resource.dll
0x00000000c4c80000 0x00000000c4caf000 C:\Windows\SYSTEM32\dwmapi.dll
0x00000000a82f0000 0x00000000a839c000 C:\Windows\SYSTEM32\TextShaping.dll
0x000000003d580000 0x000000003d936000 E:\iniRePather-Skyrim\Mod Organizer 2\Stock Game\d3dcompiler_46e.dll
0x00000000c3660000 0x00000000c38c3000 C:\Windows\system32\d3d11.dll
0x000000003da80000 0x000000003db86000 C:\Windows\System32\DriverStore\FileRepository\nvxi.inf_amd64_237ff059771d2136\nvldumdx.dll
0x00000000bf210000 0x00000000bf241000 C:\Windows\SYSTEM32\cryptnet.dll
0x00000000bf080000 0x00000000bf1c8000 C:\Windows\SYSTEM32\drvstore.dll
0x00000000c6f20000 0x00000000c6f4c000 C:\Windows\SYSTEM32\devobj.dll
0x00000000c8d00000 0x00000000c8d1d000 C:\Windows\System32\imagehlp.dll
0x00000000c6b20000 0x00000000c6b38000 C:\Windows\System32\CRYPTSP.dll
0x00000000c6240000 0x00000000c6274000 C:\Windows\system32\rsaenh.dll
0x0000000037310000 0x0000000039c58000 C:\Windows\System32\DriverStore\FileRepository\nvxi.inf_amd64_237ff059771d2136\nvwgf2umx.dll
0x000000005a150000 0x000000005a417000 C:\Windows\system32\nvspcap64.dll
0x000000003ca30000 0x000000003d281000 C:\Windows\System32\DriverStore\FileRepository\nvxi.inf_amd64_237ff059771d2136\NvCamera\NvCamera64.dll
0x00000000c2ef0000 0x00000000c2ef7000 C:\Windows\SYSTEM32\XINPUT9_1_0.dll
0x00000000abe60000 0x00000000ac014000 C:\Windows\SYSTEM32\WindowsCodecs.dll
0x00000000a9340000 0x00000000a937b000 C:\Windows\SYSTEM32\dxcore.dll
0x000000003c620000 0x000000003ca24000 C:\Windows\System32\DriverStore\FileRepository\nvxi.inf_amd64_237ff059771d2136\NvCamera\d3dcompiler_47_64.dll
0x00000000bc100000 0x00000000bc868000 C:\Windows\system32\nvapi64.dll
0x0000000035c70000 0x000000003730f000 C:\Windows\System32\DriverStore\FileRepository\nvxi.inf_amd64_237ff059771d2136\nvcuda64.dll
0x00000000ab5e0000 0x00000000ab7bb000 C:\Windows\System32\DriverStore\FileRepository\u0368234.inf_amd64_35d00646c20862d1\B368147\aticfx64.dll
0x00000000ab820000 0x00000000ab858000 C:\Windows\System32\DriverStore\FileRepository\u0368234.inf_amd64_35d00646c20862d1\B368147\atiuxp64.dll
0x00000000a94c0000 0x00000000ab3be000 C:\Windows\System32\DriverStore\FileRepository\u0368234.inf_amd64_35d00646c20862d1\B368147\atidxx64.dll
0x00000000c4990000 0x00000000c4a20000 C:\Windows\SYSTEM32\apphelp.dll
0x00000000ab7f0000 0x00000000ab81f000 C:\Windows\SYSTEM32\amdihk64.dll
0x00000000a5550000 0x00000000a55cd000 C:\Windows\System32\OneCoreCommonProxyStub.dll
0x00000000b4910000 0x00000000b50d9000 C:\Windows\System32\OneCoreUAPCommonProxyStub.dll
0x00000000c3e90000 0x00000000c4074000 C:\Windows\SYSTEM32\dcomp.dll
0x000000003a050000 0x000000003a34e000 E:\iniRePather-Skyrim\Mod Organizer 2\mods\????-SKSE Plugin Chinese\SKSE\Plugins\ChineseInput\rime.dll
0x000000003c130000 0x000000003c1bb000 C:\Windows\SYSTEM32\XAudio2_7.dll
0x00000000bfe50000 0x00000000bfed5000 C:\Windows\System32\MMDevApi.dll
0x00000000c4c60000 0x00000000c4c74000 C:\Windows\SYSTEM32\resourcepolicyclient.dll
0x0000000077ff0000 0x0000000078172000 C:\Windows\SYSTEM32\AUDIOSES.DLL
0x00000000c6740000 0x00000000c678b000 C:\Windows\SYSTEM32\powrprof.dlla
0x00000000c65b0000 0x00000000c65c2000 C:\Windows\SYSTEM32\UMPDC.dll
0x00000000b77c0000 0x00000000b7901000 C:\Windows\System32\Windows.UI.dll
0x00000000b74f0000 0x00000000b7591000 C:\Windows\System32\WindowManagementAPI.dll
0x00000000bf430000 0x00000000bf630000 C:\Windows\SYSTEM32\twinapi.appcore.dll
0x00000000c0c20000 0x00000000c0c2a000 C:\Windows\SYSTEM32\avrt.dll
0x0000000050e60000 0x0000000050efc000 C:\Windows\SYSTEM32\DSOUND.DLL
0x00000000b8ca0000 0x00000000b8cc6000 C:\Windows\SYSTEM32\winmmbase.dll
0x00000000a4730000 0x00000000a4741000 C:\Windows\SYSTEM32\xinput1_4.dll
0x00000000ae500000 0x00000000aec37000 C:\Program Files\NVIDIA Corporation\NvContainer\MessageBus.dll
0x00000000c7fc0000 0x00000000c7fc8000 C:\Windows\System32\NSI.dll
0x00000000c0a40000 0x00000000c0a5d000 C:\Windows\SYSTEM32\dhcpcsvc.DLL

Stack trace:

Frame 0: SkyrimSE.exe+0x3aa7e3
Frame 1: SkyrimSE.exe+0x6b03f9
Frame 2: SkyrimSE.exe+0xc32a81
Frame 3: SkyrimSE.exe+0xc34c48
Frame 4: SkyrimSE.exe+0xc0d6bd
Frame 5: KERNEL32.DLL+0x17034
Frame 6: ntdll.dll+0x52651

**Comment by ersh1** [comment]
Should be fixed since 1.0.1
